version: '3.8'

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    restart: always
    ports:
      - "1521:1521"  # Porta para conectar ao banco
      - "5500:5500"  # Porta do Oracle Enterprise Manager
    environment:
      ORACLE_PWD: "12345678"  # Definição da senha do usuário SYS e SYSTEM
    volumes:
      - oradata:/opt/oracle/oradata  # Volume para persistência dos dados
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/12345678@localhost/XEPDB1", "as", "sysdba", "exit"]
      interval: 30s
      retries: 5
      start_period: 60s

volumes:
  oradata:
    driver: local
